/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        sagar: {
          canvas: '#f6f9fc',
          canvasAlt: '#edf5fa',
          canvasWarm: '#faf8f5',
          powder: '#e0f2fe',
          seafoam: '#e6f7f2',
          aqua: '#e0f7fa',
          cyan: '#e6fffa',
          lavender: '#f3f0ff',
          coralLight: '#fff2eb',
          coral: '#ea580c',
          panel: '#ffffff',
          panelMuted: '#f1f7fc',
          card: '#ffffff',
          cardAlt: '#eef6fb',
          border: '#cfdce8',
          borderLight: '#e4edf5',
          borderAccent: '#93c5fd',
          deep: '#0a192f',
          navy: '#0f1f38',
          charcoal: '#1e293b',
          slate: '#334155',
          textMuted: '#64748b',
          textDark: '#0f172a',
          textBright: '#0a192f',
          accent: '#0284c7',
          accentHover: '#0369a1',
          accentLight: '#38bdf8',
        },
        // Backward-compatibility alias
        orca: {
          dark: '#0a192f',
          navy: '#0f1f38',
          teal: '#0284c7',
          cyan: '#38bdf8',
          blue: '#0369a1',
          surface: '#f1f7fc',
          border: '#cfdce8',
        },
        // Strict Maritime Semantic Risk Tokens (Crisp & High Contrast Outdoors)
        risk: {
          safe: {
            DEFAULT: '#059669',
            badgeBg: '#ecfdf5',
            badgeBorder: '#a7f3d0',
            badgeText: '#065f46',
            bannerBg: '#f0fdf4',
            bannerBorder: '#86efac',
            icon: '#059669',
          },
          moderate: {
            DEFAULT: '#d97706',
            badgeBg: '#fffbeb',
            badgeBorder: '#fde68a',
            badgeText: '#92400e',
            bannerBg: '#fffbeb',
            bannerBorder: '#fcd34d',
            icon: '#d97706',
          },
          high: {
            DEFAULT: '#ea580c',
            badgeBg: '#fff7ed',
            badgeBorder: '#fed7aa',
            badgeText: '#9a3412',
            bannerBg: '#fff7ed',
            bannerBorder: '#fdba74',
            icon: '#ea580c',
          },
          severe: {
            DEFAULT: '#dc2626',
            badgeBg: '#fef2f2',
            badgeBorder: '#fecaca',
            badgeText: '#991b1b',
            bannerBg: '#fef2f2',
            bannerBorder: '#f87171',
            icon: '#dc2626',
          },
          unknown: {
            DEFAULT: '#475569',
            badgeBg: '#f8fafc',
            badgeBorder: '#e2e8f0',
            badgeText: '#334155',
            bannerBg: '#f8fafc',
            bannerBorder: '#cbd5e1',
            icon: '#475569',
          },
        },
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        'soft-sm': '0 1px 3px rgba(15, 31, 56, 0.05)',
        'soft-md': '0 4px 14px -2px rgba(15, 31, 56, 0.08), 0 2px 6px -1px rgba(15, 31, 56, 0.04)',
        'soft-lg': '0 10px 25px -4px rgba(15, 31, 56, 0.1), 0 4px 10px -2px rgba(15, 31, 56, 0.04)',
        'soft-xl': '0 20px 35px -8px rgba(15, 31, 56, 0.12), 0 8px 16px -4px rgba(15, 31, 56, 0.06)',
        'ocean-glow': '0 0 20px rgba(56, 189, 248, 0.25)',
      },
      animation: {
        'wave-flow': 'waveFlow 18s cubic-bezier(0.36, 0.45, 0.63, 0.53) infinite',
        'wave-slow': 'waveFlow 28s cubic-bezier(0.36, 0.45, 0.63, 0.53) infinite',
        'float-gentle': 'floatGentle 6s ease-in-out infinite',
      },
      keyframes: {
        waveFlow: {
          '0%': { transform: 'translateX(0)' },
          '50%': { transform: 'translateX(-25%)' },
          '100%': { transform: 'translateX(0)' },
        },
        floatGentle: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-6px)' },
        },
      },
    },
  },
  plugins: [],
}
