"""
Planner Node — Intent Extraction & Advisory Synthesis

The Planner is the entry point and exit point of the ORCA workflow.
It is the ONLY component that communicates directly with the fisher.

Phase 1 (planner_intake):
    - Parse natural language into structured Trip Context
    - Check for required fields
    - Ask for missing critical information — never guess

Phase 2 (planner_synthesize):
    - Read Risk Evidence JSON
    - Generate human-readable advisory explanation
    - Translate to fisher's language if needed (via Bhashini)

Reference: 08_AI_ML_AGENTIC_ARCHITECTURE.md, Section 4
"""

from __future__ import annotations

from datetime import datetime, timezone

from app.graph.state import OrcaState, AgentExecution


def planner_intake(state: OrcaState) -> OrcaState:
    """Phase 1: Extract intent from the fisher's message and validate trip context.

    This node:
    1. Parses the latest user message for trip parameters.
    2. Checks for minimum required fields (origin, departure_time, vessel).
    3. Sets workflow_status to CLARIFICATION_REQUIRED or VALIDATED.

    The LLM handles understanding and extraction.
    It MUST NOT perform safety math, generate weather, or invent coordinates.
    """
    execution = AgentExecution(
        id="",  # Generated by persistence layer
        trip_id=state.get("trip_context", {}).get("trip_id", ""),
        agent_name="planner",
        status="running",
        started_at=datetime.now(timezone.utc).isoformat(),
        input_summary={"phase": "intake"},
        output_data={},
        data_sources=[],
        confidence=None,
        error=None,
    )

    # TODO: Implement LLM-based intent extraction
    # from langchain_core.messages import SystemMessage, HumanMessage
    # 1. Build prompt with system instructions
    # 2. Pass conversation_history to LLM
    # 3. Parse structured output (trip_context fields)
    # 4. Check for missing required fields
    # 5. Set workflow_status accordingly

    # --- Stub: mark as validated for graph compilation ---
    trip = state.get("trip_context", {})
    vessel = state.get("vessel_profile", {})

    required_trip = ["origin", "departure_time_iso"]
    missing = [f for f in required_trip if not trip.get(f)]

    if not vessel.get("beam_width_m"):
        missing.append("beam_width_m")

    if missing:
        state["workflow_status"] = "CLARIFICATION_REQUIRED"
        execution["status"] = "completed"
        execution["output_data"] = {"missing_fields": missing}
    else:
        state["workflow_status"] = "VALIDATED"
        execution["status"] = "completed"
        execution["output_data"] = {"validated": True}

    execution["completed_at"] = datetime.now(timezone.utc).isoformat()

    # Append execution record
    executions = state.get("agent_executions", [])
    executions.append(execution)
    state["agent_executions"] = executions

    return state


def planner_synthesize(state: OrcaState) -> OrcaState:
    """Phase 2: Synthesize Risk Evidence into a human-readable advisory.

    This node:
    1. Reads the risk_evidence from state.
    2. Generates a fisher-friendly recommendation using LLM.
    3. Translates to the fisher's language if needed.

    The LLM synthesizes and explains.
    It MUST NOT override the Risk Engine's advisory_category or risk_level.
    """
    execution = AgentExecution(
        id="",
        trip_id=state.get("trip_context", {}).get("trip_id", ""),
        agent_name="planner",
        status="running",
        started_at=datetime.now(timezone.utc).isoformat(),
        input_summary={"phase": "synthesis"},
        output_data={},
        data_sources=[],
        confidence=None,
        error=None,
    )

    risk = state.get("risk_evidence", {})
    category = risk.get("advisory_category", "INSUFFICIENT_INFORMATION")

    # TODO: Implement LLM-based advisory synthesis
    # 1. Build prompt with risk evidence, weather, marine context
    # 2. Generate recommendation_text, reason, affected_phase, etc.
    # 3. Translate via Bhashini if fisher's language != "en"

    # --- Stub advisory ---
    state["advisory"] = {
        "advisory_category": category,
        "recommendation_text": f"Advisory based on {category}.",
        "reason": "Stub — LLM synthesis not yet implemented.",
        "affected_phase": "",
        "affected_time": "",
        "affected_location": "",
        "vessel_context": "",
        "evidence_summary": "",
        "uncertainty_notes": "",
        "disclaimer": "PathFinder provides decision support only. Follow official alerts.",
        "language": "en",
    }
    state["workflow_status"] = "ADVISORY_READY"

    execution["status"] = "completed"
    execution["completed_at"] = datetime.now(timezone.utc).isoformat()
    execution["output_data"] = {"advisory_category": category}

    executions = state.get("agent_executions", [])
    executions.append(execution)
    state["agent_executions"] = executions

    return state
